name: build
on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '*.md'

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install libgdiplus
        if: startsWith(matrix.os, 'macOS')
        run: brew install mono-libgdiplus
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Run PixelPet tests
        run: dotnet run --project Tests --configuration Release --no-build
